apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: attestation-sidecar-secure
  namespace: raj-compliance-dashboard
  labels:
    app: attestation-sidecar-secure
    app.kubernetes.io/component: attestation-sidecar
    app.kubernetes.io/instance: attestation-sidecar-secure
    app.kubernetes.io/name: attestation-sidecar
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: attestation-sidecar-secure:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.sidecar
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secret: secure-sidecar-generic-secret
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: attestation-sidecar-secure
  namespace: raj-compliance-dashboard
  labels:
    app: attestation-sidecar-secure
    app.kubernetes.io/component: attestation-sidecar
    app.kubernetes.io/instance: attestation-sidecar-secure
spec:
  lookupPolicy:
    local: false